# Site settings
title: "에이전틱 SaaS 조직"
subtitle: "100배 생산성과 고수익 성장을 위한 청사진"
description: "AI 에이전트 기반의 자율적 소프트웨어 개발 조직 구축을 위한 포괄적인 가이드 시리즈"
baseurl: ""
url: "https://kronenz.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  series:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation
navigation:
  - title: "홈"
    url: "/"
  - title: "AI 기반 개발"
    url: "/ai-development/"
  - title: "자동화 팩토리"
    url: "/automation-factory/"
  - title: "팀 관리"
    url: "/team-management/"
  - title: "고급 아키텍처"
    url: "/advanced-architecture/"
  - title: "비즈니스 성장"
    url: "/business-growth/"
  - title: "리소스"
    url: "/resources/"

# SEO
seo:
  type: "WebSite"
  locale: "ko_KR"
  site_name: "에이전틱 SaaS 조직"
  description: "AI 에이전트 기반의 자율적 소프트웨어 개발 조직 구축을 위한 포괄적인 가이드 시리즈"

# Social
social:
  - name: "GitHub"
    icon: "github"
    url: "https://github.com/kronenz"
  - name: "Email"
    icon: "envelope"
    url: "mailto:contact@kronenz.dev"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .gitignore
  - .git
  - tools/
  - examples/
  - templates/
  - "*.json"
  - "continuity-report*.json"
